### ISSUE TITLE
generate changelog from fixed tag 0.1.0

### ISSUE THREAD

**Issue by plastikfan** [snivilised/lucretia#23]
this is experimental to help understand how the [Release Changelog Builder](https://github.com/marketplace/actions/release-changelog-builder) github action works.

**Comment by plastikfan** [comment]
This did NOT work, generated a changelog with no changes. I was expecting all the relevant commit from 0.1.0 to 0.1.4 to be generated.

```yaml
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: "./config/changelog.config.json"
          fromTag: "0.1.0"
```

perhaps you also need __toTag__
